name: gzc_app
description: "云尚公证处"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1
  flutter: ^3.32.7

dependencies:
  flutter: 
    sdk: flutter
  get: ^4.7.3
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  path_provider: ^2.1.5
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  get_it: ^9.1.1
  injectable: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
