name: gzc_app
description: "云尚公证处"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1
  flutter: ^3.32.7

dependencies:
  flutter: 
    sdk: flutter
  flutter_riverpod: ^3.0.3
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  path_provider: ^2.1.5
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  get_it: ^9.1.1
  injectable: ^2.7.0
  json_annotation: ^4.9.0
  toastification: ^3.0.3
  webview_flutter: ^4.13.0
  share_plus: ^12.0.1
  go_router: ^17.0.0
  flutter_slidable: ^4.0.3
  timelines_plus: ^1.0.8
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  injectable_generator: ^2.7.0
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets:
    - lib/core/assets/images/
