name: gzc_app
description: "云尚公证处"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1
  flutter: ^3.32.7

dependencies:
  flutter: 
    sdk: flutter
  dio: ^5.9.0
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
